#!/usr/bin/env -S python3 -u -O

import sys
import time

# Display how arguments were passed through env -S
print("sys.executable =", sys.executable)
print("sys.argv       =", sys.argv)

# Confirm Python flags were applied
print("optimized mode =", __debug__ == False)

print("Hello from Python!")

input("Press Enter to exit...")
